### ISSUE TITLE
Folders with folder notes will not expand or collapse.

### ISSUE THREAD

**Issue by Madmaxneo** [aidenlx/alx-folder-note#64]
After the last update to Folder Note I can no longer expand or collapse (if expanding is forced by using "Reveal File in Navigation" if there is a link to the note) any folder that has a folder note. 
EDIT: Another who is having this issue says if you switch back to the default theme it starts working properly again. Apparently this is an issue with ITS themes.

**Comment by se-cung-syu-ngai** [comment]
I too was having this issue until I realized it was because I was using a snippet that hid the arrows next to folders. I disabled the snippet and was once again able to open folders, but it's a bit of a pain to have to aim specifically at the tiny arrows expand folders. I hope this is fixed in future updates.

**Comment by Madmaxneo** [comment]
> I too was having this issue until I realized it was because I was using a snippet that hid the arrows next to folders. I disabled the snippet and was once again able to open folders, but it's a bit of a pain to have to aim specifically at the tiny arrows expand folders. I hope this is fixed in future updates.

I hope so also. I did not have that option turned on so there were no arrows to select. Someone else mentioned this and now at least I can expand and collapse folders by selecting that tiny arrow.
